name: app_games_rating
description: Avaliações e Comentários de Jogos

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^3.2.2+1
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  http: ^0.13.3
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2

  dropdown_search: ^0.6.1
  cool_alert: ^1.1.0
  date_field: ^2.0.1

  # Autenticações
  firebase_core: ^1.2.1
  firebase_auth: ^1.3.0
  google_sign_in: ^5.0.4
  # flutter_facebook_auth: ^3.4.1

dev_dependencies:
  flutter_modular_test: ^1.0.1
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1+3
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/icon.png"
  image_path_android: "assets/images/icon.png"
  adaptive_icon_background: "assets/images/background.png"
  adaptive_icon_foreground: "assets/images/foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/google.jpg
    - assets/images/facebook.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900

scripts:
  builder: flutter packages pub run build_runner build --delete-conflicting-outputs
  icons: flutter pub run flutter_launcher_icons:main